kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc-claim
  labels:
    app: postgres
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi